# Pandas Basics

In this notebook, I will learn how to create, inspect, filter, and analyze tabular data using Pandas.

These skills will help me work with historical stock price data.

## Topics

- Series and DataFrame
- Creating a DataFrame
- Viewing rows
- Selecting columns
- Filtering data
- Basic statistics
- Missing values

In [1]:
import pandas as pd

print("Pandas version:", pd.__version__)

Pandas version: 3.0.3

In [2]:
stock_data = {
    "Date": [
        "2026-07-01",
        "2026-07-02",
        "2026-07-03",
        "2026-07-04",
        "2026-07-05"
    ],
    "Close": [100, 102, 101, 105, 108],
    "Volume": [1000, 1200, 900, 1500, 1700]
}

df = pd.DataFrame(stock_data)

df

         Date  Close  Volume
0  2026-07-01    100    1000
1  2026-07-02    102    1200
2  2026-07-03    101     900
3  2026-07-04    105    1500
4  2026-07-05    108    1700

## My Notes

A DataFrame is a table made of rows and columns.

Each column represents a variable, and each row represents one observation.

In this example, the columns are Date, Close, and Volume.

In [3]:
print("First rows:")
display(df.head())

print("Last rows:")
display(df.tail())

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

First rows:

         Date  Close  Volume
0  2026-07-01    100    1000
1  2026-07-02    102    1200
2  2026-07-03    101     900
3  2026-07-04    105    1500
4  2026-07-05    108    1700

Last rows:

         Date  Close  Volume
0  2026-07-01    100    1000
1  2026-07-02    102    1200
2  2026-07-03    101     900
3  2026-07-04    105    1500
4  2026-07-05    108    1700

Shape: (5, 3)
Columns: ['Date', 'Close', 'Volume']

In [4]:
close_prices = df["Close"]

print(close_prices)

0    100
1    102
2    101
3    105
4    108
Name: Close, dtype: int64

In [5]:
high_price_days = df[df["Close"] > 102]

high_price_days

         Date  Close  Volume
3  2026-07-04    105    1500
4  2026-07-05    108    1700

## My Notes

Filtering allows me to select rows that satisfy a condition.

For example, I can select days where the closing price or trading volume is above a certain value.

In [6]:
print("Mean closing price:", df["Close"].mean())
print("Minimum closing price:", df["Close"].min())
print("Maximum closing price:", df["Close"].max())
print("Mean volume:", df["Volume"].mean())

Mean closing price: 103.2
Minimum closing price: 100
Maximum closing price: 108
Mean volume: 1260.0

In [7]:
df.describe()

            Close       Volume
count    5.000000     5.000000
mean   103.200000  1260.000000
std      3.271085   336.154726
min    100.000000   900.000000
25%    101.000000  1000.000000
50%    102.000000  1200.000000
75%    105.000000  1500.000000
max    108.000000  1700.000000

In [8]:
df["Price_Change"] = df["Close"].diff()

df

         Date  Close  Volume  Price_Change
0  2026-07-01    100    1000           NaN
1  2026-07-02    102    1200           2.0
2  2026-07-03    101     900          -1.0
3  2026-07-04    105    1500           4.0
4  2026-07-05    108    1700           3.0

In [9]:
print(df.isnull())

    Date  Close  Volume  Price_Change
0  False  False   False          True
1  False  False   False         False
2  False  False   False         False
3  False  False   False         False
4  False  False   False         False

## My Notes

NaN means that a value is missing or cannot be calculated.

The first price change is NaN because there is no previous day to compare it with.

Missing values must be checked before using data in a machine learning model.

In [10]:
df["Date"] = pd.to_datetime(df["Date"])

print(df.dtypes)

Date            datetime64[us]
Close                    int64
Volume                   int64
Price_Change           float64
dtype: object

## What I Learned

In this notebook, I learned how to create and inspect a Pandas DataFrame.

I selected columns, filtered rows, calculated basic statistics, added new columns, and checked missing values.

I also converted the Date column into a datetime data type.

These operations will help me prepare and analyze real historical stock price data.